/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.27
 * Generated at: 2018-04-07 08:28:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/east_good/Tomcat%208.5/wtpwebapps/fts/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1523018626300L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <title>Login</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    #register {\r\n");
      out.write("      display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top-ma {\r\n");
      out.write("      margin-top: 80px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top-mi {\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top-mii {\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .bottom {\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left {\r\n");
      out.write("      padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .onit {\r\n");
      out.write("      pointer-events: auto;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\" col-md-8 col-md-offset-2\">\r\n");
      out.write("        <h1 id=\"title\">登录&nbsp;\r\n");
      out.write("          <small>收藏、上传、下载</small>\r\n");
      out.write("        </h1>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 panel panel-default top-ma\" id=\"login\">\r\n");
      out.write("        <form method=\"post\" class=\"form-horizontal col-md-10 col-md-offset-1 top-mi\" id=\"loginForm\" autocomplete=\"off\" action=\"/fts/users/logIn.action\">\r\n");
      out.write("          <div class=\"form-group form-group-lg\">\r\n");
      out.write("            <label class=\"control-label\" for=\"inputUsername\">用户名</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"inputUsername\" name=\"ftsUsers.userName\" data-toggle=\"popover\" data-container=\"body\" data-placement=\"right\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group form-group-lg has-feedback\">\r\n");
      out.write("            <label class=\"control-label\" for=\"inputPassword\">密码</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"inputPassword\" name=\"ftsUsers.password\" data-toggle=\"popover\" data-container=\"body\" data-placement=\"right\">\r\n");
      out.write("            <span class=\"onit top-mii left glyphicon glyphicon-eye-close form-control-feedback\" onclick=\"eye();\" aria-hidden=\"true\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row bottom\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary col-md-offset-7 col-sm-offset-5 col-md-2 col-sm-3 col-xs-12 bottom\" id=\"gotoRegister\">去注册</button>\r\n");
      out.write("            <input type=\"button\" class=\"btn btn-success col-md-offset-1 col-sm-offset-1 col-md-2 col-sm-3 col-xs-12\" id=\"loginsubmit\"\r\n");
      out.write("              value=\"登录\" onclick=\"loginCheck();\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 panel panel-default top-ma\" id=\"register\">\r\n");
      out.write("        <form method=\"post\" class=\"form-horizontal col-md-10 col-md-offset-1 top-mi\" id=\"registerForm\" autocomplete=\"off\" action=\"/fts/users/submitUsers.action\">\r\n");
      out.write("          <div class=\"form-group form-group-lg\">\r\n");
      out.write("            <label class=\"control-label\" for=\"inputRUsername\">用户名</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control rgForm\" id=\"inputRUsername\" name=\"ftsUsers.userName\" data-toggle=\"popover\" data-container=\"body\" data-placement=\"right\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group form-group-lg\">\r\n");
      out.write("            <label class=\"control-label\" for=\"inputREmail\">邮箱</label>\r\n");
      out.write("            <input type=\"email\" class=\"form-control rgForm\" id=\"inputREmail\" name=\"ftsUsers.email\" data-toggle=\"popover\" data-container=\"body\" data-placement=\"right\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group form-group-lg has-feedback\">\r\n");
      out.write("            <label class=\"control-label\" for=\"inputRPassword\">密码</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control rgForm\" id=\"inputRPassword\" name=\"ftsUsers.password\" data-toggle=\"popover\" data-container=\"body\" data-placement=\"right\">\r\n");
      out.write("            <span class=\"onit top-mii left glyphicon glyphicon-eye-close form-control-feedback\" onclick=\"eye('R');\" aria-hidden=\"true\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group form-group-lg has-feedback\">\r\n");
      out.write("            <label class=\"control-label\" for=\"inputResPassword\">重复输入密码</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control rgForm\" id=\"inputResPassword\" data-toggle=\"popover\" data-container=\"body\" data-placement=\"right\">\r\n");
      out.write("            <span class=\"onit top-mii left glyphicon glyphicon-eye-close form-control-feedback\" onclick=\"eye('Res');\" aria-hidden=\"true\"></span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row bottom\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary col-md-offset-7 col-sm-offset-5 col-md-2 col-sm-3 col-xs-12 bottom\" id=\"gotoLogin\">去登录</button>\r\n");
      out.write("            <input type=\"button\" class=\"btn btn-success col-md-offset-1 col-sm-offset-1 col-md-2 col-sm-3 col-xs-12\" id=\"registersubmit\"\r\n");
      out.write("              value=\"注册\" onclick=\"registerCheck();\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- bootstrap -->\r\n");
      out.write("  <!-- <script src=\"https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js\"></script> -->\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/user.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
